version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=ellen
            - MYSQL_DATABASE=ellen
            - MYSQL_USER=ellen
            - MYSQL_PASSWORD=ellen
        ports:
            - '3308:3306'